#!/usr/bin/env bash
# =============================================================================
# config.sh — FreeVoice default configuration
# =============================================================================
# Do NOT edit this file for personal settings. Instead, copy
# config.local.sh.example to config.local.sh and edit that file.
# config.local.sh is gitignored and will never be overwritten by updates.
# =============================================================================

# -----------------------------------------------------------------------------
# Whisper binary
# -----------------------------------------------------------------------------
# Auto-detects the whisper-cli installed by Homebrew.
# Override in config.local.sh if you built whisper.cpp from source.
WHISPER_BIN="${WHISPER_BIN:-$(command -v whisper-cli 2>/dev/null || echo "")}"

# -----------------------------------------------------------------------------
# Model file
# -----------------------------------------------------------------------------
# Path to the Whisper GGML model. Run install.sh to download a model.
#
# Recommended choices:
#   ggml-small.en.bin  — ~150 MB, ~2-5 s latency  (default, good balance)
#   ggml-medium.en.bin — ~470 MB, ~8-15 s latency (higher accuracy)
#   ggml-base.en.bin   — ~75 MB,  ~1-2 s latency  (fastest, lower quality)
WHISPER_MODEL="${WHISPER_MODEL:-$HOME/.freevoice/models/ggml-small.en.bin}"

# -----------------------------------------------------------------------------
# Microphone / audio input device
# -----------------------------------------------------------------------------
# ":default" uses whatever macOS has set as the system default input device.
# If you plug in a USB mic and set it as the default in System Settings → Sound,
# it will be picked up automatically — no config change needed.
#
# To target a specific device by index (e.g. if you have multiple mics and
# don't want to change the system default), run `freevoice.sh list-devices`
# to find the index, then override in config.local.sh: MIC_DEVICE=":1"
MIC_DEVICE="${MIC_DEVICE:-:default}"

# -----------------------------------------------------------------------------
# Recording quality
# -----------------------------------------------------------------------------
# Whisper is trained on 16 kHz mono audio — no benefit to recording higher.
RECORD_SAMPLE_RATE="${RECORD_SAMPLE_RATE:-16000}"
RECORD_CHANNELS="${RECORD_CHANNELS:-1}"

# -----------------------------------------------------------------------------
# Transcription language
# -----------------------------------------------------------------------------
# "en" for English-only models (faster). Use "auto" for auto-detect with
# multilingual models (ggml-small, ggml-medium without the .en suffix).
WHISPER_LANGUAGE="${WHISPER_LANGUAGE:-en}"

# -----------------------------------------------------------------------------
# Paste behavior
# -----------------------------------------------------------------------------
# Whether to automatically paste into the active app after transcription.
# Set to "false" to only copy to clipboard (paste manually with Cmd+V).
AUTO_PASTE="${AUTO_PASTE:-true}"

# Whether to append a trailing space after the pasted text.
# Useful so the next word you type doesn't run into the transcription.
APPEND_TRAILING_SPACE="${APPEND_TRAILING_SPACE:-true}"

# -----------------------------------------------------------------------------
# Notifications
# -----------------------------------------------------------------------------
# Show macOS banner notifications for recording state and errors.
SHOW_NOTIFICATIONS="${SHOW_NOTIFICATIONS:-true}"

# -----------------------------------------------------------------------------
# Temporary files
# -----------------------------------------------------------------------------
FREEVOICE_TMPDIR="${FREEVOICE_TMPDIR:-/tmp}"
